spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    show-sql: true
jwt:
  issuer: hello@example.com
  secret: hello-world-asdfdsafa-asdfsadfsdafdsafdsafsa